apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: training-notification
spec:
  tls:
    - hosts:
        - training-notification.example.com
      secretName: training-notification-tls
  rules:
    - host: training-notification.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: training-notification
                port:
                  name: http
