apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: training-notification
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
images:
  - name: ghcr.io/maru3022/training_notification
    newTag: latest
